export interface Project {
  slug: string;
  title: string;
  category: string;
  description: string;
  longDescription: string;
  tags: string[];
  accent: string;
  liveUrl?: string;
  githubUrl?: string;
  year: string;
  role: string;
  features: string[];
  challenges: string[];
  results: string[];
}

export const projects: Project[] = [
  {
    slug: "quotehub",
    title: "QuoteHub",
    category: "Marketplace",
    description: "A modern marketplace connecting freelancers with clients, featuring real-time bidding and secure payments.",
    longDescription: "QuoteHub is a full-stack marketplace platform that bridges the gap between freelancers and businesses. Built with performance and user experience in mind, it features real-time bidding, secure escrow payments, and an intelligent matching algorithm.",
    tags: ["Next.js", "TypeScript", "Tailwind CSS", "MongoDB", "Stripe"],
    accent: "#FF9E5E",
    liveUrl: "https://quotehub.example.com",
    githubUrl: "https://github.com/dammybundlez/quotehub",
    year: "2024",
    role: "Full Stack Developer",
    features: ["Real-time bidding system", "Secure escrow payments", "AI-powered matching", "Real-time chat", "Responsive dashboard"],
    challenges: ["Implementing real-time features with WebSockets", "Building a secure payment flow", "Optimizing database queries for performance"],
    results: ["50% faster matching process", "99.9% payment success rate", "4.8/5 user satisfaction rating"],
  },
  {
    slug: "velvet-and-roots",
    title: "Velvet & Roots",
    category: "E-Commerce",
    description: "An e-commerce platform for a premium hair care brand with subscription boxes and personalized recommendations.",
    longDescription: "Velvet & Roots is a luxury hair care e-commerce experience that combines stunning visuals with seamless functionality. The platform features personalized product recommendations, subscription management, and a blog with hair care tips.",
    tags: ["React", "Node.js", "Stripe", "Framer Motion", "PostgreSQL"],
    accent: "#C98B8B",
    liveUrl: "https://velvetandroots.example.com",
    githubUrl: "https://github.com/dammybundlez/velvet-and-roots",
    year: "2024",
    role: "Frontend Developer",
    features: ["Personalized recommendations", "Subscription management", "Interactive product catalog", "Integrated blog", "Smooth animations"],
    challenges: ["Building a recommendation engine", "Implementing complex subscription logic", "Creating smooth page transitions"],
    results: ["35% increase in conversions", "50% reduction in cart abandonment", "2x average order value"],
  },
  {
    slug: "grace-chapel",
    title: "Grace Chapel",
    category: "Church Website",
    description: "A community-focused church website with event management, sermon archives, and online giving integration.",
    longDescription: "Grace Chapel's digital home provides a welcoming online experience for both current members and visitors. The site features sermon streaming, event registration, small group finder, and secure online giving.",
    tags: ["Next.js", "Tailwind CSS", "Sanity CMS", "Vercel"],
    accent: "#E3C878",
    liveUrl: "https://gracechapel.example.com",
    githubUrl: "https://github.com/dammybundlez/grace-chapel",
    year: "2023",
    role: "Full Stack Developer",
    features: ["Live sermon streaming", "Event calendar", "Small group finder", "Online giving", "CMS-powered blog"],
    challenges: ["Integrating live streaming", "Building a complex event system", "Ensuring accessibility for all users"],
    results: ["3x increase in online engagement", "40% more event registrations", "60% increase in online giving"],
  },
  {
    slug: "taskflow",
    title: "TaskFlow",
    category: "SaaS",
    description: "A project management tool with Kanban boards, team collaboration, and real-time updates.",
    longDescription: "TaskFlow is a modern project management solution designed for agile teams. It features drag-and-drop Kanban boards, real-time collaboration, task dependencies, and detailed analytics.",
    tags: ["React", "TypeScript", "Socket.io", "PostgreSQL"],
    accent: "#6366F1",
    liveUrl: "https://taskflow.example.com",
    year: "2024",
    role: "Frontend Developer",
    features: ["Drag-and-drop Kanban", "Real-time collaboration", "Task dependencies", "Analytics dashboard", "Team management"],
    challenges: ["Implementing real-time sync across clients", "Building smooth drag-and-drop UX", "Handling complex state management"],
    results: ["45% improvement in team productivity", "30% faster project delivery", "4.9/5 user rating"],
  },
  {
    slug: "bites",
    title: "Bites",
    category: "Food Delivery",
    description: "A food delivery platform with real-time order tracking, restaurant dashboard, and payment integration.",
    longDescription: "Bites is a comprehensive food delivery platform connecting hungry customers with local restaurants. Features include real-time GPS tracking, restaurant management dashboard, and seamless payment processing.",
    tags: ["Next.js", "Tailwind CSS", "Prisma", "Stripe"],
    accent: "#EF4444",
    liveUrl: "https://bites.example.com",
    year: "2023",
    role: "Full Stack Developer",
    features: ["Real-time GPS tracking", "Restaurant dashboard", "Payment integration", "Order history", "Rating system"],
    challenges: ["Implementing real-time location tracking", "Building a complex ordering system", "Optimizing for mobile performance"],
    results: ["25% faster delivery times", "40% increase in repeat orders", "4.7/5 app store rating"],
  },
  {
    slug: "finova",
    title: "Finova",
    category: "Fintech",
    description: "A personal finance dashboard with expense tracking, budgeting tools, and investment insights.",
    longDescription: "Finova empowers users to take control of their finances with intuitive tracking, smart budgeting, and investment insights. The platform connects to bank accounts and provides real-time financial health monitoring.",
    tags: ["React", "Chart.js", "Node.js", "MongoDB"],
    accent: "#10B981",
    liveUrl: "https://finova.example.com",
    year: "2024",
    role: "Frontend Developer",
    features: ["Expense tracking", "Budget planning", "Investment portfolio", "Bank integration", "Financial insights"],
    challenges: ["Building complex data visualizations", "Ensuring data security", "Handling real-time financial data"],
    results: ["Users save 20% more on average", "90% user retention rate", "Featured on Product Hunt"],
  },
  {
    slug: "learnly",
    title: "Learnly",
    category: "EdTech",
    description: "An online learning platform with video courses, progress tracking, and interactive quizzes.",
    longDescription: "Learnly makes education accessible and engaging with high-quality video courses, interactive quizzes, and personalized learning paths. The platform supports both instructors and students with comprehensive tools.",
    tags: ["Next.js", "TypeScript", "AWS", "Tailwind CSS"],
    accent: "#8B5CF6",
    liveUrl: "https://learnly.example.com",
    year: "2023",
    role: "Full Stack Developer",
    features: ["Video courses", "Interactive quizzes", "Progress tracking", "Certificates", "Discussion forums"],
    challenges: ["Building a video streaming infrastructure", "Implementing progress tracking", "Creating an engaging learning experience"],
    results: ["10K+ active learners", "95% course completion rate", "4.8/5 instructor rating"],
  },
  {
    slug: "staybnb",
    title: "Staybnb",
    category: "Booking",
    description: "A vacation rental platform with property listings, booking system, and host management.",
    longDescription: "Staybnb connects travelers with unique accommodations worldwide. The platform features property listings with rich media, secure booking, host management tools, and a review system.",
    tags: ["React", "Node.js", "MongoDB", "Mapbox"],
    accent: "#F59E0B",
    liveUrl: "https://staybnb.example.com",
    year: "2024",
    role: "Frontend Developer",
    features: ["Property listings", "Booking system", "Host dashboard", "Map integration", "Review system"],
    challenges: ["Building a complex booking calendar", "Implementing map-based search", "Creating a trust-based review system"],
    results: ["5K+ properties listed", "98% booking success rate", "4.9/5 guest satisfaction"],
  },
  {
    slug: "pulse",
    title: "Pulse",
    category: "Health & Fitness",
    description: "A fitness tracking app with workout plans, progress analytics, and social features.",
    longDescription: "Pulse helps users achieve their fitness goals with personalized workout plans, detailed progress tracking, and a supportive community. The app integrates with health devices for comprehensive monitoring.",
    tags: ["React Native", "TypeScript", "Firebase", "HealthKit"],
    accent: "#EC4899",
    liveUrl: "https://pulse.example.com",
    year: "2023",
    role: "Mobile Developer",
    features: ["Workout plans", "Progress analytics", "Social features", "Health integration", "Custom routines"],
    challenges: ["Building cross-platform mobile app", "Integrating with health APIs", "Creating engaging social features"],
    results: ["50K+ downloads", "4.8/5 app store rating", "Featured in Health & Fitness"],
  },
  {
    slug: "artify",
    title: "Artify",
    category: "Creative Platform",
    description: "A digital art marketplace connecting artists with collectors, featuring NFT integration.",
    longDescription: "Artify empowers digital artists to showcase and sell their work to a global audience. The platform features NFT minting, auction functionality, and a curated gallery experience.",
    tags: ["Next.js", "TypeScript", "Solidity", "IPFS"],
    accent: "#14B8A6",
    liveUrl: "https://artify.example.com",
    year: "2024",
    role: "Full Stack Developer",
    features: ["NFT minting", "Auction system", "Artist profiles", "Curated galleries", "Wallet integration"],
    challenges: ["Integrating blockchain technology", "Building a secure auction system", "Creating a seamless UX for Web3"],
    results: ["1K+ artists onboarded", "$100K+ in sales", "Featured on CoinDesk"],
  },
];

export function getProjectBySlug(slug: string): Project | undefined {
  return projects.find((p) => p.slug === slug);
}
